<?php


/**
 * This class defines the structure of the 'kp_setting' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * śro, 9 cze 2010, 01:19:21
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package kpPropelSettingsPlugin
 * @author  Krzysztof Pyrkosz (http://www.pyrkosz.pl/)
 * @author  Brent Shaffer <bshaffer@centresource.com>
 */
class KpSettingTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.kpPropelSettingsPlugin.lib.model.map.KpSettingTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('kp_setting');
		$this->setPhpName('KpSetting');
		$this->setClassname('KpSetting');
		$this->setPackage('plugins.kpPropelSettingsPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 255, null);
		$this->addColumn('TYPE', 'Type', 'VARCHAR', false, 255, 'input');
		$this->addColumn('WIDGET_OPTIONS', 'WidgetOptions', 'LONGVARCHAR', false, null, null);
		$this->addColumn('VALUE', 'Value', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SETTING_GROUP', 'SettingGroup', 'VARCHAR', false, 255, '');
		$this->addColumn('SETTING_DEFAULT', 'SettingDefault', 'LONGVARCHAR', false, null, '');
		$this->addColumn('SLUG', 'Slug', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // KpSettingTableMap
